### PR TITLE
Hospitals map

### LINKED ISSUE #12: Create a Map that display the hospitals location
**Is your feature request related to a problem? Please describe.**
Create a Leaflet Map that display the hospitals location on a map

**Describe the solution you'd like**
We would like to have a map on which we can vizualise all hospitals data

### PR DESCRIPTION
**Pull request by medimessarat**
### This fix #12 
Capture

### Branch ready to be merged

### CODE REVIEW

**Comment by mohammedi-haroune** [comment]
Didn't work for me:
```
Failed to compile.

./src/App.js
Module not found: Can't resolve './HospitalsMap' in '/home/mohammedi/workspace/red-crescent-webapp/src'
``

**Comment by medimessarat** [comment]
@mohammedi-haroune  Can you please, retest with git pull and restarting server, because it works for me

**Comment by mohammedi-haroune** [comment]
> @mohammedi-haroune Can you please, retest with git pull and restarting server, because it works for me

It works now, sorry

**Comment by mohammedi-haroune** [comment]
I suggest we use https://material-ui.com/components/drawers/ to list the hospitals.

**Comment by mohammedi-haroune** [comment]
What should be done before merging is the following:
1. make the source of truth (the data) of the list and the map the same.
2. Add a drawer to list the hospitals, clicking them go to the position in the map and the pop up (we can put the same `HospitalCard` as it is) show up.
3. Eventually, a search bar

**Comment by mohammedi-haroune** [comment]
We could be inspired by https://github.com/traccar/traccar-web/tree/modern/modern
Their layout looks good, they are using the same stack: `react` and `react-leaflet`

**Comment by mohammedi-haroune** [comment]
It's farily easy to put the card as pop on the Map's markers. I tried it here's the result.
Screenshot from 2019-11-28 13-39-25
Screenshot from 2019-11-28 13-39-28

**Comment by medimessarat** [comment]
# Hospitals Map
## Map
The map now have the button to come back to the landing page
map

## HospitalCard
We can see the hospital when we click in a marker, and we have **ONLY ONE SOURCE OF DATA, hospitals.json**, location => localisation fixed.
hospital

## This fix #12 And branch ready to be merged.

**Pull request merged**
