### PR TITLE
Feat[create-react-app]: Create The React App (red-crescent-app)

### PR DESCRIPTION
**Pull request by medimessarat**
Create all the react packages, Including the MATERIAL-UI package.

### CODE REVIEW

**Comment by mohammedi-haroune** [comment]
The source code should be top level, we shouln't have the nested `red-crescent-app` inside. 
See here: https://github.com/ui-router/sample-app-react and here: https://github.com/Kentico/kontent-sample-app-react for how it should be.

**Comment by medimessarat** [comment]
@mohammedi-haroune  Yeah, i understand. i'm going to do it right now

**Comment by medimessarat** [comment]
@mohammedi-haroune  it's done #2. source code is top level.

**Comment by mohammedi-haroune** [comment]
We never repeat the same commit twice, it's  frustrating, like you've done the same thing twice!
Instead, either:
1. Revert the first and start again
2. Wright another commit, explaining what was the problem of the previous commit.

**Comment by mohammedi-haroune** [comment]
content of the README.md file of the create-react-app should be merged with the one in the repo.

**Comment by medimessarat** [comment]
#2 FIXED. Ready to be merged.

**Pull request merged**
