### PR TITLE
Contact page

### PR DESCRIPTION
**Pull request by medimessarat**
# Contact Page changes

## Landing Page 
landing

## Contact 
contact

### CODE REVIEW

**Comment by mohammedi-haroune** [comment]
What's the difference between this one and the other: #15 ?

**Comment by mohammedi-haroune** [comment]
The hospitals button is not working for me.

**Comment by medimessarat** [comment]
@mohammedi-haroune the contact view is the same, except the new button that redirect to the landing page is added, and the big changes here, is that there is now routing and linking between views which wasn't there in the previous PR.

**Comment by medimessarat** [comment]
@mohammedi-haroune, this branch is contact-page, i spent all my time on finishing contact-page and routes that will link between views, starting with ladingPage to contact and vice-ver-sa, but as now the most complex work is done, it would be a matter of two instructions to link to the hospitals. Also hospitals-map is still not operational because the card are not in the marker

**Comment by mohammedi-haroune** [comment]
The PR is a request to merge a branch (which is `contact-page` in this case).
Although this PR: #15 concerns the same branch (which is `contact-page` in this case).

**Comment by medimessarat** [comment]
@mohammedi-haroune ok thank you, sorry for this i thought i should open another PR, and close the previous one because of the changes that happened

**Comment by mohammedi-haroune** [comment]
OK. Never mind. We'll continue on this one.

**Pull request merged**
