### PR TITLE
Contact page

### LINKED ISSUE #11: Build Contact-Page for user to contact us
**Is your feature request related to a problem? Please describe.**
Create a contact page, where user can send a message to someone in the blood donor organizers and staff. 
**Describe the solution you'd like**
make a form that will give him fields, about his email to respond to him, name, object of the message, and content of the message.

### PR DESCRIPTION
**Pull request by medimessarat**
# Contact Page
PR_contact1

With information about the user sender: **name**, **email**, **subject** of the message and **message**

## Validation
Validate the different fields, and indicate the specific error for each field
PR_contact2

## Sending Email
When fields are valid The Email is sent to the adress : **redcrescentwebapp@gmail.com** . Createad for this purpose
PR_contact3

## Message Received
Here's the format of the message

PR_contact4

### **This fix #11 and Branch ready to be merged**

### CODE REVIEW

**Comment by mohammedi-haroune** [comment]
Hey! Good job.
One remark: the context part of the git commit message should be a little bit general. For example all the commits above, you could have used: `Contact` as context.

**Comment by medimessarat** [comment]
@mohammedi-haroune  Ok, thank you. I'll remember it next time.

**Comment by mohammedi-haroune** [comment]
@MediMESS, The context is like tags, it could help understand where your modification affected. In fact we should have defined them before IMHO.

**Comment by medimessarat** [comment]
@mohammedi-haroune  Ok thank you.

**Comment by mohammedi-haroune** [comment]
Je pense que les messages "message non envoyé" et "message envoyé" peuvent être implmenter avec https://material-ui.com/components/snackbars/.

ça donnera un meilleur rendu à mon avis.

**Comment by medimessarat** [comment]
It looks nice, but i would like to keep it as it is.

**Comment by mohammedi-haroune** [comment]
I've got errors when trying to test the branch
```
Failed to compile.

./src/App.js
Attempted import error: 'Contact' is not exported from './views'.
```

**Comment by mohammedi-haroune** [comment]
This was closed by mistake, work is moved to #20

**Pull request closed without merging**
